# Logging profiles for GeoServer applications

# default profile:
spring:
  profiles:
    group:
      debug:
        - "logging_debug"
        - "logging_debug_catalog"
        - "logging_debug_acl"
logging:
  level:
    root: warn
    org.springframework: warn
    org.springframework.retry: warn
    org.springframework.cloud.bus: info
    org.springframework.jdbc.support: info
    com.zaxxer.hikari.pool: warn
    # log flooding with "INFO Resolving eureka endpoints via configuration"
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: warn
    # geotools roots
    org.geotools: info
    org.geotools.util.factory: warn
    org.geotools.referencing.factory: warn
    org.geowebcache.config.XMLConfiguration: error
    # geoserver roots
    org.geotools.autoconfigure: info
    oshi.hardware.platform.linux: error
    oshi.software.os: error
    org.geoserver: warn
    org.geoserver.catalog.datadir: info
    org.geoserver.catalog.datadir.internal: warn
    org.geoserver.catalog.plugin: info
    org.geoserver.jackson: info
    org.geotools.jackson: info
    org.geoserver.platform: error
    org.geoserver.platform.resource.MemoryLockProvider: info
    org.geoserver.platform.resource.NioFileLockProvider: info
    org.geoserver.platform.resource.FileLockProvider: info
    org.geoserver.jdbcconfig: info
    org.geoserver.security: info
    org.geoserver.cloud.security: info
    # gs-acl roots
    org.geoserver.acl: info
    # gs-cloud roots
    org.geoserver.cloud: info
    org.geoserver.cloud.autoconfigure: info
    org.geoserver.cloud.config.factory: info
    # bus debugging
    org.geoserver.cloud.bus: info
    org.geoserver.cloud.event: info
    org.springframework.cloud.bus.BusAutoConfiguration: info
    org.springframework.cloud.bus.DefaultBusPathMatcher: info

---
spring.config.activate.on-profile: logging_debug
logging:
  level:
    root: info
    org.springframework: info
    # geoserver roots
    org.geoserver: info
    org.geoserver.catalog: debug
    org.geoserver.jackson: debug
    org.geotools.jackson: debug
    org.geoserver.platform.resource.MemoryLockProvider: info
    org.geoserver.platform.resource.NioFileLockProvider: debug
    org.geoserver.platform.resource.FileLockProvider: debug
    org.geoserver.security: debug
    org.geoserver.cloud.security: debug
    # gs-cloud roots
    org.geoserver.cloud: debug
    org.geoserver.cloud.config: debug
    org.geoserver.cloud.autoconfigure: trace
    org.geoserver.cloud.config.factory: trace
    org.geoserver.cloud.gwc: debug
    # bus debugging
    org.geoserver.cloud.bus: trace
    org.geoserver.cloud.event: debug
    org.springframework.cloud.bus: debug
    org.springframework.cloud.bus.BusAutoConfiguration: info
    org.springframework.cloud.bus.DefaultBusPathMatcher: info

---
spring.config.activate.on-profile: logging_debug_catalog
logging:
  level:
    # geoserver roots
    org.geoserver.catalog: debug
    org.geoserver.catalog.datadir: debug
    # gs-cloud roots
    org.geoserver.catalog.plugin: debug
    org.geoserver.cloud.autoconfigure.catalog.backend: debug
    org.geoserver.cloud.catalog.backend: debug

---
spring.config.activate.on-profile: logging_debug_events
logging:
  level:
    org.geoserver.cloud.autoconfigure.catalog.event: debug
    org.geoserver.cloud.autoconfigure.event.bus: debug
    org.geoserver.cloud.event: debug
    org.geoserver.cloud.bus: trace
    org.springframework.cloud.bus: debug
    org.springframework.cloud.bus.BusAutoConfiguration: info
    org.springframework.cloud.bus.DefaultBusPathMatcher: info

---
spring.config.activate.on-profile: logging_debug_acl
logging:
  level:
    org.geoserver.acl: debug
    org.geoserver.acl.plugin: debug
    org.geoserver.acl.api.client: debug
